apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
              name: mysqlport
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-script
              mountPath: /docker-entrypoint-initdb.d # To create the database (Run .sh, .sql, .sql.gz scripts), place the configmap in this location.
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD ping"
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "128m"
              memory: "256Mi"
            limits:
              cpu: "512m"
              memory: "512Mi"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-script
          configMap:
            name: mysql-configmap
