apiVersion: v1
kind: LimitRange
metadata:
  namespace: dummy
  name: dummy-limitrange
spec:
  limits:
    - default:
        cpu: "1000m"
        memory: "1024Mi"
      defaultRequest:
        cpu: "256m"
        memory: "256Mi"
      type: Container
