apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-service
  labels:
    app: usermgmt-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-service
  template:
    metadata:
      labels:
        app: usermgmt-service
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command:
            [
              "sh",
              "-c",
              'while ! nc -z mysql-service 3306; do sleep 2; printf "WIP"; done; echo -e " >> DB has started";',
            ]
      containers:
        - name: usermgmt-service
          image: stacksimplify/kube-usermanagement-microservice:1.0.0
          ports:
            - containerPort: 8095
          env:
            - name: DB_HOSTNAME
              value: "mysql-rds"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "usermgmtdb"
            - name: DB_USERNAME
              value: "dbadmin"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          livenessProbe:
            exec:
              command: ["sh", "-c", "nc -z localhost 8095"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 8095
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "128m"
              memory: "256Mi"
            limits:
              cpu: "512m"
              memory: "512Mi"
