apiVersion: v1
kind: Service
metadata:
  name: usermgmt
  labels:
    app: usermgmt-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: usermgmt-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8095
