apiVersion: v1
kind: Service
metadata:
  name: mysql-service # Keep the name of the service the same as the deployment. It will look good when used for connection strings.
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
