kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets
spec:
  serviceAccountName: hemi-eks-secrets-reader
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - name: mysecret2
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: mysecret2
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "dummy-secret"
