apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dummy-secret
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "eksworkshop"
        objectType: "secretsmanager"
