apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.4
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
          command:
            - "redis-server"
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          volumeMounts:
            - mountPath: /redis-master
              name: config
            - name: data
              mountPath: /redis-master-data
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-conf
            items:
              - key: redis-config
                path: redis.conf
