apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-service
  namespace: wordpress
spec:
  selector:
    app: wordpress
    tier: mysql
  ports:
    - port: 3306
  clusterIP: None #Headless service
