apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aks-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aks-clusterrole
subjects:
  - kind: Group
    name: 71be1339-ba5e-48db-856c-88c9e5b8ef1f
