apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-dev
  namespace: dev
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
      - "batch"
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]
