apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
  namespace: php-guestbook
  labels:
    app: redis
    tier: backend
    role: leader
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: leader
        tier: backend
    spec:
      containers:
        - name: redis-leader
          image: docker.io/redis:6.0.5
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  namespace: php-guestbook
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  selector:
    app: redis
    role: leader
    tier: backend
  ports:
    - port: 6379
      targetPort: 6379
