apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  namespace: php-guestbook
  labels:
    app: redis
    tier: backend
    role: follower
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: follower
        tier: follower
    spec:
      containers:
        - name: redis-follower
          image: gcr.io/google_samples/gb-redis-follower:v2
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: php-guestbook
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  selector:
    app: redis
    role: follower
    tier: backend
  ports:
    - port: 6379
