apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
    version: v1
spec:
  containers:
    - name: myapp
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
