apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: redis
      volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
        - name: bar
          mountPath: "/etc/bar"
  volumes:
    - name: foo
      secret:
        secretName: redis-pass
        items:
          - key: password
            path: data
    - name: bar
      secret:
        secretName: redis-pass1
