apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  labels:
    name: myapp1
spec:
  containers:
    - name: myapp1
      image: redis
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: redis-pass
              key: password
        - name: password
          valueFrom:
            secretKeyRef:
              key: password1
              name: redis-pass1
