apiVersion: v1
kind: Pod
metadata:
  name: myapp-vol
  labels:
    name: myapp-vol
spec:
  containers:
    - name: myapp-vol
      image: redis
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: credentials
          mountPath: /etc/cred
  volumes:
    - name: credentials
      secret:
        secretName: redis-pass
